### ISSUE TITLE
Error: cannot unmarshal string into Go value of type uint64 in personal_unlock_account

### ISSUE THREAD

**Issue by Eugenpaul** [EthWorks/ethereum.rb#13]
There is an error when I try to use personal_unlock_account from Client.

```
irb> client = Ethereum::HttpClient.new('http://localhost:8545')
=> #<Ethereum::HttpClient:0x000000040a2ae0 @id=0, @log=false, @batch=nil, @formatter=#<Ethereum::Formatter:0x000000040a2ab8>, @gas_price=22000000000, @gas_limit=4000000, @host="localhost", @port=8545, @ssl=false, @uri=#<URI::HTTP http://localhost:8545>>

irb> client.personal_unlock_account("0x<address>", "<password>", 30)
IOError: invalid argument 2: json: cannot unmarshal string into Go value of type uint64
        from (irb):3
```

It seems that the problem is in conversion of integer to hex string, which is not needed in this case. I resolved it by adding an exception for this particular function - not to call encode_params on its args . Should I prepare a pull request?

**Comment by marekkirejczyk** [comment]
As far as I remember personal unlock_account is deprecated due to security reasons. Especially with http mode. You should instead:

-  unlock CLI option with IPC connection (not so good) or
-  (better) use signed transactions (take a look here: https://github.com/EthWorks/ethereum.rb/releases/tag/2.1.0).

**Comment by kurotaky** [comment]
@Eugenpaul 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
